const navList = [{
  title: '访客接口',
  id: '001',
  link: '/',
  disabled: false,
  subNavList: [{
    title: '访客预约',
    index: '001001',
    link: '/'
  }, {
    title: '访客信息',
    index: '001002',
    link: '/'
  }, {
    title: '访客黑名单',
    index: '001003',
    link: '/'
  }, {
    title: '访客记录查询',
    index: '001004',
    link: '/'
  }, {
    title: '岗亭管理',
    index: '001005',
    link: '/'
  }, {
    title: '日志管理',
    index: '001006',
    link: '/'
  }]
}, {
  title: '考勤接口(x)',
  id: '002',
  link: '/',
  disabled: true,
  subNavList: [{
    title: '考勤点设置',
    index: '002001',
    link: '/'
  }, {
    title: '考勤规则设置',
    index: '002002',
    link: '/'
  }, {
    title: '班次设置',
    index: '002003',
    link: '/'
  }, {
    title: '班组设置',
    index: '002004',
    link: '/'
  }, {
    title: '排班设置',
    index: '002005',
    link: '/'
  }, {
    title: '考勤调整',
    index: '002006',
    link: '/'
  }, {
    title: '考勤日志',
    index: '002007',
    link: '/'
  }, {
    title: '报表统计',
    index: '002008',
    link: '/'
  }]
}, {
  title: '门禁接口',
  id: '003',
  link: '/',
  disabled: false,
  subNavList: [{
    title: '设备管理',
    index: '003001',
    link: '/'
  }, {
    title: '开门计划',
    index: '003002',
    link: '/'
  }, {
    title: '门组权限',
    index: '003003',
    link: '/'
  }, {
    title: '按人授权',
    index: '003004',
    link: '/'
  }, {
    title: '按门授权',
    index: '003005',
    link: '/'
  }, {
    title: '发卡复核(x)',
    index: '003006',
    link: '/'
  }, {
    title: '门通道控制',
    index: '003007',
    link: '/'
  }, {
    title: '记录查询',
    index: '003008',
    link: '/'
  }, {
    title: '设备状态日志',
    index: '003009',
    link: '/'
  }, {
    title: '服务查询',
    index: '003010',
    link: '/'
  }]
}, {
  title: '人员卡片接口',
  id: '004',
  link: '/',
  disabled: false,
  subNavList: [{
    title: '人员管理',
    index: '004001',
    link: '/'
  }, {
    title: '卡片管理',
    index: '004002',
    link: '/'
  }]
}, {
  title: '梯控接口(x)',
  id: '005',
  link: '/',
  disabled: true,
  subNavList: [{
    title: '梯控管理',
    index: '005001',
    link: '/'
  }, {
    title: '梯控授权',
    index: '005002',
    link: '/'
  }]
}, {
  title: '系统配置接口(x)',
  id: '006',
  link: '/',
  disabled: true,
  subNavList: [{
    title: '节假日配置',
    index: '006001',
    link: '/'
  }, {
    title: '身份配置',
    index: '006002',
    link: '/'
  }]
}, {
  title: '消费接口',
  id: '007',
  link: '/',
  disabled: false,
  subNavList: [{
    title: '营业单位管理',
    index: '007001',
    link: '/'
  }, {
    title: '消费设备',
    index: '007002',
    link: '/'
  }, {
    title: '规则设置',
    index: '007003',
    link: '/'
  }, {
    title: '充值管理',
    index: '007004',
    link: '/'
  }, {
    title: '日志查询',
    index: '007005',
    link: '/'
  }, {
    title: '报表统计',
    index: '007006',
    link: '/'
  }, {
    title: '参数设置',
    index: '007007',
    link: '/'
  }, {
    title: '消费授权',
    index: '007008',
    link: '/'
  }]
}, {
  title: '巡更接口(x)',
  id: '008',
  link: '/',
  disabled: true,
  subNavList: [{
    title: '巡更点设置',
    index: '008001',
    link: '/'
  }, {
    title: '班组设置',
    index: '008002',
    link: '/'
  }, {
    title: '线路设置',
    index: '008003',
    link: '/'
  }, {
    title: '排班设置',
    index: '008004',
    link: '/'
  }, {
    title: '记录查询',
    index: '008005',
    link: '/'
  }, {
    title: '报表统计',
    index: '008006',
    link: '/'
  }]
}]

export {
  navList
}
